### ISSUE TITLE
How do you install Ubuntu after you build it

### ISSUE THREAD

**Issue by ghost** [tobhe/ubuntu-asahi#1]

**Comment by tobhe** [comment]
Have a look at https://tobhe.de/ubuntu/install to see how I hook into the [asahi installer](https://github.com/AsahiLinux/asahi-installer). If you want to install a local image you will need to point INSTALLER_DATA to your own installer_data.json and REPO_BASE to a url hosting your image.

Unless you plan to modify the image in a significant way it is probably easier to install my prebuilt image as documented in the README and then modify it to your liking after installation.
