### ISSUE TITLE
Display output is not active

### ISSUE THREAD

**Issue by OumarBalde04** [tobhe/ubuntu-asahi#100]
These are my issues I don't know where is my fault

<img width="1470" alt="Scherm­afbeelding 2024-03-14 om 16 59 21" src="https://github.com/UbuntuAsahi/ubuntu-asahi/assets/160843171/1688b6e1-0518-4399-9ed2-b19ef3245146">
<img width="1470" alt="Scherm­afbeelding 2024-03-14 om 16 59 08" src="https://github.com/UbuntuAsahi/ubuntu-asahi/assets/160843171/239ec565-7bb3-4101-a353-a44124995689">

**Comment by OumarBalde04** [comment]
for the record I got a MacBook Air m2 2023

**Comment by tobhe** [comment]
Looks like you are trying to boot something in QEMU. Ubuntu Asahi provides bare metal Ubuntu images for Apple Silicon macs, we can't help you with running Ubuntu in a VM. Regular Ubuntu ARM installer images are available at https://ubuntu.com/download/server/arm
