### ISSUE TITLE
Brightness Monitor Control

### ISSUE THREAD

**Issue by maitreverge** [tobhe/ubuntu-asahi#101]
Hi ! 

I've been searching around for quite some time different solutions to control my external monitor brightness.

I tried :
updating `grub` settings
installing `kubuntu desktop`
`xrandr` command,
`brightness-controller` package
`light` package
`brightnessctl` package
`brightness-controller` package

I am running out of ideas, and my monitor refuse to cooperate regarding self brightness control.

I tweaked every above solutions, read package documentation, and failed to reach the brightness control.

Hardware : Mac Mini M1.
Ubuntu 23.01

Hope someone could help !

**Comment by eslerm** [comment]
`ddcutil` might work

I don't have a Mini to test

**Comment by maitreverge** [comment]
Did not work, but thanks for showing me a precious package ! I guess I'll wait for a native support....

**Comment by eslerm** [comment]
@maitreverge do you have any success changing the brightness with `echo 32 | sudo tee /sys/class/backlight/X/brightness ` where `32` is a number between 0 and 256 and `X` is the external display?

**Comment by maitreverge** [comment]
@eslerm Thanks for your interest in the issue !
I did try your take, and the directory `/sys/class/backlight/` is empty.

I honestly gave up, and told myself that not having backlight control is a tradeoff for having Ubuntu on a Mac M1, _or maybe such feature is maybe not available yet..._

I really appreciated your answer tho, I'll close the issue from now, hopping for something to happen !

Thanks for your time !
