### ISSUE TITLE
Ubuntu Server 22.04.4 LTS support?

### ISSUE THREAD

**Issue by devnoname120** [tobhe/ubuntu-asahi#104]
I'm trying to use my recently-acquired Mac Mini M1 as a self-hosted server. I see that this project supports Ubuntu Desktop but I don't see a mention of Ubuntu Server: neither in the repository nor in the GitHub issues.

I much prefer to run Ubuntu Server because Ubuntu Desktop is bloated with unnecessary services that are intertwined with the OS and can easily break it when removing them. Additionally the attack surface is smaller thanks to the reduced number of services, the lack of a desktop environment, etc.

Is there a way to run Ubuntu Server with this project? I could imagine that Ubuntu Server is very close to Ubuntu Desktop (just with less features) so there shouldn't be a reason why it wouldn't work with minimal changes. Can you confirm? 

Thank you!

**Comment by eslerm** [comment]
Please note that `EXPERT=1` must be set when running the installer for the 22.04 option.
