### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Mravinko** [tobhe/ubuntu-asahi#106]
MacBook Pro 2021, installation stopped right after I chose OS type with `zipfile.BadZipFile: File is not a zip file` error.

[installer.log](https://github.com/UbuntuAsahi/ubuntu-asahi/files/15015921/installer.log)

**Comment by eslerm** [comment]
From your logs, it looks like you are using the old installer link (`INSTALLER_DATA`).

Could you please try `curl -sL https://ubuntuasahi.org/install | sh` ?

If that does not work, please report *and* try again in a few hours. There was a server change and uptime has been lower than usual.

**Comment by PhilStollery** [comment]
I get the same error - trying to download a zip from https://files.tobhe.de/ubuntu/os/ubuntu-desktop-23.10-20240209.zip that doesn't exist.

**Comment by PhilStollery** [comment]
[installer.log](https://github.com/UbuntuAsahi/ubuntu-asahi/files/15016245/installer.log)

**Comment by eslerm** [comment]
Thanks @PhilStollery 

@tobhe is out sick and likely won't be able to work on this for a little while

**Comment by PhilStollery** [comment]
> Thanks @PhilStollery
> 
> @tobhe is out sick and likely won't be able to work on this for a little while

He must be keeping an eye on this - it's now fixed.

**Comment by Mravinko** [comment]
Thanks for quick fix

**Comment by tobhe** [comment]
Thanks for the reports everyone, managed to deploy a quick fix yesterday. I'll have to come up with a better solution once I find more time.
