### ISSUE TITLE
Unable to install – no OS selection

### ISSUE THREAD

**Issue by Rastafabisch** [tobhe/ubuntu-asahi#11]
I cannot install anything as I'm not offered any choice. I typed in `Ubuntu 22.10 Desktop` and similar but this led to no avail.

> For reference: I ran this install script: `curl -sL https://tobhe.de/ubuntu/install | bash`

<img width="773" alt="OS Selection" src="https://user-images.githubusercontent.com/38974866/218896161-b4bf0cae-6c37-48c4-a037-e4db6a519b83.png">

**Comment by tobhe** [comment]
Thanks for the report, I have not seen this before. What kind of hardware are you using? Is this one of the new M2 machines?

**Comment by Rastafabisch** [comment]
I am using a MacBook Pro M1 Pro. I have done some testing (comparing it to stalk Asahi and think now, that the issue is, that I try to install on an external drive. I suppose there is now support as of now, and it will take some time until "upstream" Asahi implements this, so feel free to close the issue. Sorry for the noise.

**Comment by tobhe** [comment]
That would make sense, I have never tried that. It might be worth to make the installer show a clearer error message in this case, but that would need to be done in https://github.com/AsahiLinux/asahi-installer
