### ISSUE TITLE
KDE's charge limit does not work

### ISSUE THREAD

**Issue by Consistos** [tobhe/ubuntu-asahi#117]
Battery charges to 100% despite settting it to 75%.

**Comment by Consistos** [comment]
The settings are not saved despite displaying so after applying: going to an other energy config tab and back resets the 2 charge limit settings to 100% and 99%. This only applies to them in the advanced energy config panel.
(commenting instead of editing so no one take the wrong lead)

**Comment by eslerm** [comment]
@Consistos do you know if this issue occurs in official Ubuntu releases under amd64?

**Comment by Consistos** [comment]
It works after [creating the following udev rule](https://social.treehouse.systems/@AsahiLinux/110560192550506827):
```echo 'SUBSYSTEM=="power_supply", KERNEL=="macsmc-battery", ATTR{charge_control_end_threshold}="80"' | sudo tee /etc/udev/rules.d/10-battery.rules```.

**Comment by tobhe** [comment]
Thank you for debugging it! I'll see if we can add that to one of our packages

**Comment by mkurz** [comment]
I am not sure if it is a good idea to put this rule in one of your packages.

**Comment by tobhe** [comment]
Thanks @mkurz, replied before I properly read it. I assumed it was a fix for kde and not a hard configured limit :) Anyway, we should still try to find a solution for KDE then.
