### ISSUE TITLE
Audio not working on 2020 Mac M1 Air

### ISSUE THREAD

**Issue by Sakurokamiamy** [tobhe/ubuntu-asahi#129]
I checked all the settings and I am running 22.04 LTS but it doesn't work. Is there any way to download a driver or get the audio working?

**Comment by tobhe** [comment]
Hey @Sakurokamiamy, Audio is not supported on 22.04. I recommend upgrading to 24.04 to get all the newest features.

**Comment by Sakurokamiamy** [comment]
okay then, by the way is there any chance that audio will be available on 22.04 at some point? Just asking, and thank you!

**Comment by tobhe** [comment]
Probably not. There is just too much infrastructure missing that we would have to backport. Keep in mind 22.04 is from 2022, which is older than audio support in Asahi.
