### ISSUE TITLE
"Metal"-support for GPU? (M1)

### ISSUE THREAD

**Issue by InfiniteBSOD** [tobhe/ubuntu-asahi#140]
Hello,

First off: Thank you for bringing Ubuntu to Apple Silicon.

I'm on a MBP 16" with M1 and just now installed Ubuntu Asahi, I compared my installation of "hashcat" on Ubuntu Asahi vs Mac OS X and the results are extremely different:
Ubuntu: MD5 362 MH/s
Mac OS X: MD5 6628MH/s

I can see that on Mac OS X hashcat utilizes "Metal" whereas on Ubuntu Asahi hashcat utilizes OpenCL.

I'm guessing "[metal](https://developer.apple.com/metal/)" only works on Mac OS X so having such a support in Linux / Ubuntu Asahi isn't possible?

Best Regards

**Comment by Base64WasTaken** [comment]
Confirmed. Ubuntu does not support metal to my knowledge.

**Comment by tobhe** [comment]
Hey, you are right, there is no metal support on Ubuntu or Linux in general and I wouldn't get my hopes up that it will ever be supported. We only recently enabled opencl support so I expect there will be performance improvements over time.

**Comment by InfiniteBSOD** [comment]
Appreciate the response.

A question which my friend might open up a separate issue for:
He has a MBP 16"  (M2) and AFAIK when I (on my M1 MBP) launched hashcat it reported that OpenCL worked OOB.
He however doesn't have any drivers for OpenCL.
I can't for the life of me remember that I downloaded any OpenCL drivers.

Does the drivers for OpenCL need to be downloaded separately? He ran update & upgrade without success.

**Comment by tobhe** [comment]
Try installing `mesa-opencl-icd`. It might have been pulled in as a dependency of something on your machine.

**Comment by InfiniteBSOD** [comment]
> Try installing `mesa-opencl-icd`. It might have been pulled in as a dependency of something on your machine.

Appreciate it!
My friend got it working.
Thanks so much.
Closing.
