### ISSUE TITLE
24.10 Oracular Oriole support

### ISSUE THREAD

**Issue by Rad0van** [tobhe/ubuntu-asahi#145]
Hi,

is there any plan to support 24.10 Oracular Oriole any time soon? Particularly I'd like to install KDE Desktop with the new Plasma 6.1

Thank you.

**Comment by tobhe** [comment]
Hey, you can install 24.04 and upgrade to 24.10 with `update-manager`. We are still working on 24.10 pre-built installer images but functionally there should be no difference.

**Comment by Rad0van** [comment]
> Hey, you can install 24.04 and upgrade to 24.10 with `update-manager`. We are still working on 24.10 pre-built installer images but functionally there should be no difference.

Oh, that's a great news. Thought I'd have to learn Fedora to get Plasma 6 on my new Mac. Thanks a lot.

**Comment by FelicianoTech** [comment]
As mentioned above, you can run Ubuntu Asahi 24.10 if you upgrade from the previous release. I was running 24.04 and just upgraded about an hour ago by running `sudo do-release-upgrade`. 

I haven't been running it long, but so far, it's been good, aside from snaps like Firefox trying to take over again. That's a Canonical problem, though, not an Ubuntu Asahi problem.

**Comment by tobhe** [comment]
Thanks for the feedback! We now also have a 24.10 installer iso so I am closing this one.
