### ISSUE TITLE
e2fsck: Get a newer version of e2fsck!

### ISSUE THREAD

**Issue by cowpod** [tobhe/ubuntu-asahi#16]
Went through a fresh installation process of Ubuntu 22.10 Desktop, and am getting a "e2fsck: Get a newer version of e2fsck!"

I'm then put into initramfs, which is too small for me to actually get a new e2fsck?

Macbook Air M2, Ventura, 16GB+512GB.

![F1BFC931-E778-4B95-BC3B-683DA2C88E91](https://user-images.githubusercontent.com/6283258/228038751-b1ae068a-37a3-4f56-8b6f-5f74a5b9aed4.jpeg)

**Comment by tobhe** [comment]
huh interesting. might be a broken image. I will generate a new one.

EDIT: I have reset the installer image to the last know working one for now. It is probably easiest for you to just reinstall with that.

**Comment by cowpod** [comment]
installed successfully, and updated everything (dist-upgrade)

**Comment by tobhe** [comment]
Fixed now. Turns out the problem was that I used a 23.04 machine to generate the image which enables ext4 features that aren't supported in 22.10. Thanks for the report!
