### ISSUE TITLE
Ubuntu 20.04 LTS Support

### ISSUE THREAD

**Issue by darebear** [tobhe/ubuntu-asahi#18]
Hello, 

Can you please/add compile images for Ubuntu 20.04 LTS? Alternatively, can you add instructions on steps to take, in conjunction with the bash script, to install a custom image? 

Thank you.

**Comment by eslerm** [comment]
We do not have plans to support Ubuntu 20.04. The M1 was released after 20.04, which means many bug fixes for Apple hardware never made it to 20.04. Rust would need to be backported into the kernel and anything to do with 16K kernel pages would be broken.

A possible workaround is running 20.04 in an LXD container or VM, if that OS is specifically needed.

Current development is focused on 22.04 LTS, the 23.04 interim release, and Ubuntu flavors.
