### ISSUE TITLE
installation of 20.04.5 ubuntu

### ISSUE THREAD

**Issue by Dinesh19102003** [tobhe/ubuntu-asahi#19]
it was a easy way to download in macm2 baremetal  but the onee 1 was looking for was the version of 20.04.5LTS

**Comment by tobhe** [comment]
Unlikely. Old software and brand new hardware don't go together. It require a lot of work to backport all the fixes to 20.04. In fact even 22.04 is not properly supported anymore and won't get graphics drivers etc. Why do you need 20.04? What could do is run the newest release bare metal and have an 20.04 lxd container.
