### ISSUE TITLE
Is there any way to fix a broken bootup using your scripts?

### ISSUE THREAD

**Issue by rick-kilgore** [tobhe/ubuntu-asahi#2]
When I run it, I only see the ability to install.  My bootup is failing with the error messages shown in this pic of my screen during bootup: https://imgur.com/LVudPjm.

**Comment by tobhe** [comment]
I believe you are hitting a bug with the current mesa version not working properly with an older kernel. You should be able to get a TTY with FN + CTRL + CMD + F2 and install linux-asahi-edge, which is a newer kernel that does work, from there.

**Comment by tobhe** [comment]
I have pushed a new kernel so `apt update && apt upgrade` should also work

**Comment by rick-kilgore** [comment]
Thank you @tobhe! I will try that if I need to try with 22.10 again. But I am currently thinking that 22.10 is just too unstable for asahi.  I dug into the problem a bit and was unable to get Xorg to run without crashing on the latest 22.10 packages from ubuntu.  Is it still possible to run 22.04 instead?

If you want me try again with 22.10, let me know.  I blew that partition away already with the plan to revert to 22.04, and then discovered that's not possible with your latest setup.

**Comment by tobhe** [comment]
I think the xorg issue on 22.10 is resolved. it was missing a 30-modeset.conf that is now shipped with the new asahi-configs package. I can reenable 22.04 if you prefer using that, but it I was not planning to backport the GPU driver.

**Comment by rick-kilgore** [comment]
That's ok, I don't seem to need the GPU for what I'm doing.  I'll benefit from it when the 22.10 changes are merged into the stable distro.

**Comment by tobhe** [comment]
Alright, I have restored the old jammy images for now. I will upload new ones when I find the time to build and test them.
