### ISSUE TITLE
Problems when setting as default boot volume during installation (M1 Pro)

### ISSUE THREAD

**Issue by bbbbbb11** [tobhe/ubuntu-asahi#27]
The last step of the installation (When the new system is installed as the one to be loaded) lasts indefinitely.

`Setting the new OS as the default boot volume...`

Tried to restart, the result is the same, decided to abort this step and try to perform further steps as it should be.
In "recovery mode" I get an error immediately when I open the terminal

Asahi Linux installer (second step)
VGID: F2CF832D-76AD-4382-9500-F434770DA54
System volume: /Volumes/ubuntu_os
Can't get local policy for Volume GrOUp VULD F20/8320-7610-4382-9688-F43467700N
4
Failed to obtain values from the current local policy logout
[Process completed]

**Comment by tobhe** [comment]
Is that your first time installing linux on the machine? I think I have seen similar errors when reinstalling too often on the same machine. If you think that might be the case there, there is a script hosted by asahi to clean up the boot entries which fixed it for me: `curl -L https://alx.sh/cleanbp | bash`. You will probably have to run the installer again after that.

**Comment by bbbbbb11** [comment]
@tobhe  Do I understand correctly that before `cleanbp` I need to manually delete the volume with the installed but not running instance?
Can you add this information to the README? As it is not an obvious thing for a user at a less advanced level of understanding.


```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0    341      0 --:--:-- --:--:-- --:--:--   344
100   381  100   381    0     0    389      0 --:--:-- --:--:-- --:--:--  2164
KEEP 3D3287DE-280D-4619-AAAB-D97469CA9C71
KEEP 4D019D7B-07E4-4825-8E1B-B2FE38E994C1
RM 5F9234CF-C7F4-496F-B5F4-646CA2537157
rm: 5F9234CF-C7F4-496F-B5F4-646CA2537157/LocalPolicy: Operation not permitted
rm: 5F9234CF-C7F4-496F-B5F4-646CA2537157: Operation not permitted
```
Tried `sudo`, but it doesn't help to solve

**Comment by tobhe** [comment]
Sorry, I should have been clearer from the start.

The uninstall process is explained here: https://asahilinux.org/2022/03/asahi-linux-alpha-release/. You best run the script from your recovery console (hold power button on boot, boot into recovery, in the top bar start a terminal). After that you can in macOS use diskutil to delete your ubuntu apfs partition as well as the efi and ext4 partitions.

Using diskutil to remove partitions is covered here: https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet
Before blindly copying any lines use `diskutil list` to find the correct partitions to remove! You don't want to remove your macOS installation on accident.

After that everything is back to normal and you are left with apfs still resized to whatever you selected in the installer before. When rerunning the installer, select "install into free space".

I agree that it is a good idea documenting this in the README, thank you for the suggestion.

**Comment by bbbbbb11** [comment]
Thank you for your detailed answer, do I understand correctly that in this case I need to remove
```
EFI EFI - UBUNT 500.2 MB disk0s4
Linux Filesystem 12.0 GB disk0s5
```
And fully `disk1`?

```
`/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:             Apple_APFS_ISC Container disk3         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk4         290.2 GB   disk0s2
   3:                 Apple_APFS Container disk1         2.5 GB     disk0s3
   4:                        EFI EFI - UBUNT             500.2 MB   disk0s4
   5:           Linux Filesystem                         12.0 GB    disk0s5
                    (free space)                         152.9 GB   -
   6:                        EFI EFI - UBUNT             500.2 MB   disk0s6
   7:           Linux Filesystem                         35.8 GB    disk0s7
   8:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s8

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +2.5 GB     disk1
                                 Physical Store disk0s3
   1:                APFS Volume ubuntu_os - Data        1.9 MB     disk1s1
   2:                APFS Volume ubuntu_os               1.1 MB     disk1s2
   3:                APFS Volume Preboot                 63.6 MB    disk1s3
   4:                APFS Volume Recovery                1.8 GB     disk1s4

/dev/disk4 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +290.2 GB   disk4
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            9.1 GB     disk4s1
   2:              APFS Snapshot com.apple.os.update-... 9.1 GB     disk4s1s1
   3:                APFS Volume Preboot                 4.8 GB     disk4s2
   4:                APFS Volume Recovery                794.5 MB   disk4s3
   5:                APFS Volume Data                    238.2 GB   disk4s5
   6:                APFS Volume VM                      20.5 KB    disk4s6`
```

**Comment by tobhe** [comment]
Those three look correct. It even seems like you actually have two incomplete installations on your machine so `disk0s6` and `disk0s7` can probably also go unless you intended to multi boot different ubuntu installations.

**Comment by bbbbbb11** [comment]
These are 2 incomplete installations.
In that case, as I wrote above, do I need to delete unnecessary partitions?
```
EFI EFI - UBUNT 500.2 MB disk0s4 
Linux Filesystem 12.0 GB disk0s5
```
and the non-starting volume?

I apologize for the endless series of clarifications, this is an important question, because I do not want to lose information through ignorance.

Anyway, i'm trying to remove unnecessary iSCPPreboots manually and recieving 
```
sudo rm -rf 5F9234CF-C7F4-496F-B5F4-646CA2537157

rm: 5F9234CF-C7F4-496F-B5F4-646CA2537157/LocalPolicy: Operation not permitted
rm: 5F9234CF-C7F4-496F-B5F4-646CA2537157: Operation not permitted

```

I think that's my problem.

**Comment by bbbbbb11** [comment]
chatGPT recommended that I do this to bypass the SIP protection.
```
sudo chflags -R nouchg,nouappnd,noschg,nosappnd 5F9234CF-C7F4-496F-B5F4-646CA2537157
sudo rm -rf 5F9234CF-C7F4-496F-B5F4-646CA2537157
```
How do you think it's safe to try this?

**Comment by tobhe** [comment]
> These are 2 incomplete installations.
In that case, as I wrote above, do I need to delete unnecessary partitions?

Yes, if you do not intend to keep any of your installations that would probably be:
```
diskutil apfs deleteContainer disk1
diskutil eraseVolume free free disk0s4
diskutil eraseVolume free free disk0s5
diskutil eraseVolume free free disk0s6
diskutil eraseVolume free free disk0s7
```
> How do you think it's safe to try this?

Can't comment on that because I have never done this. Better reboot into the recovery and use the terminal from there, that has always worked for me.
EDIT: adding to that: run the script instead of deleting anything by hand to make sure it doesn't do anything wrong.

**Comment by bbbbbb11** [comment]
I have problems with returning free space to availability, i see reduced max-space in disk utility
<img width="843" alt="image" src="https://user-images.githubusercontent.com/132914727/236907940-3903befe-8fab-4f7c-880f-8ad8cbe1c68d.png">
and I can't get that disk space back
```
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk2         292.7 GB   disk0s2
   3:                        EFI EFI - UBUNT             500.2 MB   disk0s3
                    (free space)                         206.5 GB   -

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +292.7 GB   disk2
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            9.1 GB     disk2s1
   2:              APFS Snapshot com.apple.os.update-... 9.1 GB     disk2s1s1
   3:                APFS Volume Preboot                 4.8 GB     disk2s2
   4:                APFS Volume Recovery                794.5 MB   disk2s3
   5:                APFS Volume Data                    236.7 GB   disk2s5
   6:                APFS Volume VM                      20.5 KB    disk2s6
   ```
   Can you please help me with it?

**Comment by tobhe** [comment]
Looks like you need to delete `disk0s3` too with `diskutil eraseVolume free free disk0s3` to have contiguous free space after disk2 followed by `diskutil apfs resizeContainer disk2 0` to resize it to fill up the empty space.
