### ISSUE TITLE
Add package: mesa-asahi

### ISSUE THREAD

**Issue by qwerzl** [tobhe/ubuntu-asahi#3]
Hi there,
Now that the experimental GPU driver is out, could you add mesa-asahi to the PPA?

**Comment by tobhe** [comment]
Hi @qwerzl, there is a mesa package in the ppa and the gpu driver should work out of the box, see https://launchpad.net/~tobhe/+archive/ubuntu/asahi. All you need to do is upgrade to kinetic.

**Comment by sassa7777** [comment]
how do i install it after add repo

**Comment by tobhe** [comment]
@sasa8810 If you install your ubuntu as documented in the [README](https://github.com/tobhe/ubuntu-asahi#readme) the PPA should be enabled by default. After the release upgrade you might be required to reenable it and change the version to the one you are running.

**Comment by sassa7777** [comment]
So, it’s enabled by default?

**Comment by qwerzl** [comment]
> Hi @qwerzl, there is a mesa package in the ppa and the gpu driver should work out of the box, see https://launchpad.net/~tobhe/+archive/ubuntu/asahi. All you need to do is upgrade to kinetic.

Ah I see. I was still in Jammy. Thanks for your work!
