### ISSUE TITLE
speaker support

### ISSUE THREAD

**Issue by seyedanvari** [tobhe/ubuntu-asahi#30]
the sound driver not installed in ubuntu 22.10

**Comment by tobhe** [comment]
@seyedanvari what hardware are you using? Are you trying to use aux headphones, bluetooth or speakers? On most laptops speakers are disabled on purpose just like it is on Asahi Linux because we are currently lacking safeguards to protect the hardware. Enabling speakers without those can easily permanently damage your hardware.

There is upstream work happening on implementing the bits needed to safely drive the speakers but we want to make sure everyone's hardware is safe before enabling any of this by default.

**Comment by seyedanvari** [comment]
I meant that the speaker was inactive. Thank you for your answer.

**Comment by eslerm** [comment]
hi @seyedanvari

There is speaker support in the kernel, but it is not enabled for safety reasons. There can be hardware damage if the speakers are played too loud. Upstream is aware of this, and we will add support as soon as it is available.

https://github.com/AsahiLinux/docs/wiki/Feature-Support

**Comment by PlusLake** [comment]
I can install speakersafetyd with Debian to enable speakers in my M1 Macbook Air since last week.
Can I do the same with ubuntu-asahi?

https://social.treehouse.systems/@AsahiLinux/111396388974903682

**Comment by tobhe** [comment]
@PlusLake In theory you should be able to set up the userland parts (speakersafetyd, configs, etc) by hand to get working speaker support. We are working on packaging everything up nicely and enabling it by default and that unfortunately takes a little longer. We hope to have everything in place within the next week(s).

**Comment by tobiasgrosser** [comment]
Speaker support should now be available upstream. However, the packages do not yet seem to work for me. In particular, I get the following error:

```
sudo apt install asahi-audio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following packages have unmet dependencies:
 asahi-audio : Depends: pipewire (>= 0.3.81) but 0.3.79-2 is to be installed
               Depends: wireplumber (>= 0.4.15-2~) but 0.4.14-4ubuntu1.asahi0+32~ubuntu23.10.1 is to be installed
               Recommends: lv2-bankstown but it is not installable
               Recommends: speakersafetyd but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by tobhe** [comment]
@tobiasgrosser yes, I am working on getting those packaged. bankstown is already uploaded to the asahi-testing ppa, speakersafetyd is WIP. For pipewire and wireplumber I am considering backporting the noble versions. The ones we have in mantic and especially jammy would need quite a few patches.

**Comment by PlusLake** [comment]
perform a `sudo apt update && sudo apt upgrade` few minutes ago and speaker works great now!
Big thanks to all the contributors!! :heart:

**Comment by tobiasgrosser** [comment]
This meanwhile works for me too. This issue is (partially?) addressed, I feel.

**Comment by tobhe** [comment]
Speaker support should now be enabled by default on Mantic. Jammy needs a little more work to backport all the dependencies. Glad to hear that it works for you!

**Comment by HasanTheSyrian** [comment]
> Speaker support should now be enabled by default on Mantic. Jammy needs a little more work to backport all the dependencies. Glad to hear that it works for you!

Do the speakers work on Jammy? I couldn't find anything related in the commits.

Thanks in advance.

**Comment by eslerm** [comment]
Ubuntu Asahi has moved to 9 months of Ubuntu release support. Backporting speakers packages to Jammy was a factor. Please ask to re-open issue if a supported version is affected.
