### ISSUE TITLE
Installation Clarification Questions

### ISSUE THREAD

**Issue by daver12345** [tobhe/ubuntu-asahi#35]
Still a bit new to this process, so I wanted to make sure I'm doing everything correctly. On 2020 M1 Air. Sorry if this isn't the place to put this but I just wanted to be sure of what I was doing.

I saw an issue you closed recently about installing linux-asahi-edge in order to get the new GPU drivers working, so just double checking that I understood the process correctly:
1. Install ubuntu-asahi through the installer (I just installed lunar)
2. Run the following:
$ sudo apt-get install linux-asahi-edge
$ sudo update-grub

Should I be installing a different version of mesa? I couldn’t find “mesa-asahi-edge”. 

I read the following: "The linux-asahi-edge kernel can be installed side-by-side with the standard linux-asahi package, but both versions should be kept in sync, so make sure to always update your packages together!" What should I do to keep both kernels in sync?

Also, I saw that Wayland is preferred for Plasma, but I'm not sure if this matters since I'm not using Plasma. Is it recommended?

**Comment by tobhe** [comment]
If you installed lunar you should have working GPU drivers out of the box, no further steps needed. You can install linux-asahi-edge if you want.

Currenty regular and -edge are almost identical, this might change in the future though. The idea is to introduce riskier new features in edge first before releasing them to everyone.

> Should I be installing a different version of mesa? I couldn’t find “mesa-asahi-edge”.

Not necessary. The Asahi mesa driver is enabled in our version. 

> I read the following: "The linux-asahi-edge kernel can be installed side-by-side with the standard linux-asahi package, but both versions should be kept in sync, so make sure to always update your packages together!" What should I do to keep both kernels in sync?

Regular `apt update && apt upgrade`  should be fine. If you don't install kernels by hand you should be fine.

> Also, I saw that Wayland is preferred for Plasma, but I'm not sure if this matters since I'm not using Plasma. Is it recommended?

The Apple GPUs with Asahi driver work better with Wayland. In my experience X will still work, but Wayland receives more testing and bug fixes in general.
