### ISSUE TITLE
backport updates to jammy

### ISSUE THREAD

**Issue by tobhe** [tobhe/ubuntu-asahi#37]
It looks like a good share of our user base is sticking to 22.04 LTS. It would like to backport our recent driver and mesa updates to jammy to make them available for everyone.

**Comment by yadvr** [comment]
Hi @tobhe thanks for the great work, can you confirm if the Ubuntu 22.04 kernel has kvm enabled (for running VMs) and if we can freely apt-get update pkgs or would that break things? Thanks.

**Comment by tobhe** [comment]
Hi @rohityadavcloud kvm worked last time I tried and nothing should break with package updates. If it does we will fix it.

**Comment by yadvr** [comment]
Excellent thanks for replying so quickly @tobhe

**Comment by tobhe** [comment]
Closing because jammy is now in sync with Lunar.
