### ISSUE TITLE
Touchpad cursor move is strange

### ISSUE THREAD

**Issue by MDX-Tom** [tobhe/ubuntu-asahi#39]
The cursor move is strange (not linear to the finger) compared with the native macOS. 
It seems that the original asahi Arch Linux does also have the cursor move different than that in macOS, but in Ubuntu it is much stranger.

**Comment by tobhe** [comment]
The Ubuntu behavior is probably due to gnome. You could try installing gnome-tweaks and see if there is a setting to make it more similar to macos.
Another weird thing I noticed in gnome is that the scrool speed is super sensitive.

**Comment by MDX-Tom** [comment]
ok thanks! I'll try it.
