### ISSUE TITLE
System does not reboot after 1st boot - Enters grub rescue.

### ISSUE THREAD

**Issue by tyleraiv** [tobhe/ubuntu-asahi#49]
Apparently I'm experiencing the same issue as previously described (This post is a repeat - I had mistakenly added this problem to the closed issue prior). I've attempted approx. 5 installations. Installing the Arch Linux presents no issues. I've attached the following: lsblk, grub.cfg as grub.txt and first-boot.log. These files were generated before the reboot in anticipate of the problem.  I've also included a pict of the boot screen at the failure state. It appears that the partition UUID in the failure screen is different from that of the grub file. This unit is a 2020 MacBook Air M1/8GB/256GB system. The attempts to install were all made July 17 and today July 18, 2023. Thank you.

[lsblk.txt](https://github.com/UbuntuAsahi/ubuntu-asahi/files/12095532/lsblk.txt)
[grub.txt](https://github.com/UbuntuAsahi/ubuntu-asahi/files/12095533/grub.txt)
[first-boot.log](https://github.com/UbuntuAsahi/ubuntu-asahi/files/12095540/first-boot.log)
![IMG_0102](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/139933044/e5e25432-214f-464d-80d2-152407802cf7)

**Comment by tobhe** [comment]
Thanks for the report @tyleraiv! Your logs are actually really helpful because they clearly show what's going wrong. If you just want to have a working installation you can try running `update-grub` by hand once the system is up after first boot.

For some reason grub-probe seems to pick up the old uuid. We try to prevent this by flushing udev and waiting a bit but it seems that is not enough.

**Comment by tyleraiv** [comment]
Thank you,
A reinstallation and the immediate application of update-grub has sprinkled magic dust upon my system with successful reboot the result.
Regards!

**Comment by tobhe** [comment]
Now I only need to make it so that it doesn't fail in the first place and we can live happily ever after :magic_wand:

**Comment by oliver408i** [comment]
Just installed yesterday, and the issue still exists (same issue). Yet to test to see if update-grub works
