### ISSUE TITLE
Anyone know what to do?

### ISSUE THREAD

**Issue by BadderSpider** [tobhe/ubuntu-asahi#57]
Error: 

"VID: ABDC955A-6EAE-4820-BFEF-587BB2B23098
System volume: /Volumes/user
Your system did not boot into the correct recoveryos.
Each OS in your machine comes with its own copy of recoveryos.
In order to complete the installation, we need to boot into
the brand new recoveryOS that matches the OS which you are
installing. The final installation step cannot be completed from
a different recoveryOs.
Normally this should happen automatically after the initial
installer sets up your new OS as the default boot option,
but it seems something went wrong there. Let's try that again.
Press enter to continue.

Can't load /Volumes/mattschm/usr/standalone/1386/apfs.efi
Could not load apfs.fi data from /Volumes/user/usr/standalone/i386/apfs.efi

bless failed. Did you mistype your password?
Press enter to try again."

**Comment by BadderSpider** [comment]
I don't know how to solve this Problem. 
System m1 pro 2021

**Comment by tobhe** [comment]
You failed to mention what you did before you got this error, so I will have to guess: Hold the power button while booting, wait for the boot selection menu, select ubuntu and follow the instructions on the command line.

**Comment by BadderSpider** [comment]
Oh sorry. I did exactly the Steps from the Instructions. Bit every time i get this error in the recovery os

**Comment by tobhe** [comment]
And what was the last step before you get the error?
Did you do this:
> Hold the power button while booting, wait for the boot selection menu, select ubuntu and follow the instructions on the command line.
