### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by mrsieber** [tobhe/ubuntu-asahi#66]
Installation of Ubuntu Desktop 23.04 on an iMac (M1, 2021) stopped with the error "zipfile.BadZipFile: File is not a zip file."

[installer.log](https://github.com/UbuntuAsahi/ubuntu-asahi/files/12884036/installer.log)

**Comment by tobhe** [comment]
I just updated that, let me see if I did something wrong there.

**Comment by tobhe** [comment]
Fixed, there was a typo in the file name. Thank you for the report!

**Comment by mrsieber** [comment]
Perfect, thanks!
