### ISSUE TITLE
boot hangs after updating

### ISSUE THREAD

**Issue by JoshAtticus** [tobhe/ubuntu-asahi#68]
i updated my system with sudo apt update and now it no longer boots, hanging at this screen every time
![IMG_0754](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/72828296/eb69cdd1-a765-4313-a554-260cb624b6ed)

**Comment by tobhe** [comment]
Hi @JoshAtticus. To help you figure out what's going on we need a bit more info. Which Ubuntu release are you running? when did you initially install it? When did you last update and do you remember which packages got updated?

**Comment by JoshAtticus** [comment]
> Hi @JoshAtticus. To help you figure out what's going on we need a bit more info. Which Ubuntu release are you running? when did you initially install it? When did you last update and do you remember which packages got updated?

Installed it 40 minutes before it broke, Ubuntu Desktop 23.10, updated some asahi linux and asahi apple packages

**Comment by tobhe** [comment]
I tired to replicate what you did and couldn't reproduce the problem with a plain 23.10 install and installing updates. I wonder what went wrong there.

Did you install any additional packages did you otherwise reconfigure your system by adding PPAs maybe or removing packages?

**Comment by JoshAtticus** [comment]
> I tired to replicate what you did and couldn't reproduce the problem with a plain 23.10 install and installing updates. I wonder what went wrong there.
> 
> Did you install any additional packages did you otherwise reconfigure your system by adding PPAs maybe or removing packages?

I think the system ran sudo apt autoremove at some point, maybe that could be the issue? I will try reinstalling asahi once I get home this arvo

**Comment by JoshAtticus** [comment]
Forgot to do it, remind me in 4 hours and I'll do it

**Comment by JoshAtticus** [comment]
<img width="682" alt="Screenshot 2023-11-01 at 5 43 04 pm" src="https://github.com/UbuntuAsahi/ubuntu-asahi/assets/72828296/8f4b8f30-606c-4649-a6e1-7770a68e786e">

doing the thing now

**Comment by tobhe** [comment]
Thanks for helping us debug this! I am looking forward to see if it is reproducible or if it was a random hick-up... Currently I still have no idea what might have happened.

**Comment by JoshAtticus** [comment]
Found the update that makes boot break

`ubuntu-asahi/mantic 1.16 arm64 [upgradable from: 1.15]`

**Comment by tobhe** [comment]
so it happened a second time? all this update should do is add an explicit grub dependency. did you see any other notable error messages?

**Comment by JoshAtticus** [comment]
> so it happened a second time? all this update should do is add an explicit grub dependency. did you see any other notable error messages?

yes, it happened a second time, there aren't any other error messages, it just seems to break gdm

**Comment by tobhe** [comment]
ok, I will build a new image with that version built in and see if that fixes it.

**Comment by JoshAtticus** [comment]
How do I update to it when it releases?

**Comment by JoshAtticus** [comment]
Hello, any updates?

**Comment by JoshAtticus** [comment]
It's been 5 days, any updates?

**Comment by tobhe** [comment]
Sorry for the late reply @JoshAtticus , I have been busy traveling for the last few days.
I have uploaded a new image so fresh installations _should_ not have the bug.

For your existing installation you could try to repair it from a linux usb disk. https://arvanta.net/alpine/install-alpine-m1/ documents how to create one based on alpine and how to boot it from alpine.

I also haven't yet understood why this happened only to you. Did you do anything unconventional between installing, updating and rebooting? Did you install or remove additional packages?

**Comment by JoshAtticus** [comment]
> Sorry for the late reply @JoshAtticus , I have been busy traveling for the last few days. I have uploaded a new image so fresh installations _should_ not have the bug.
> 
> For your existing installation you could try to repair it from a linux usb disk. https://arvanta.net/alpine/install-alpine-m1/ documents how to create one based on alpine and how to boot it from alpine.
> 
> I also haven't yet understood why this happened only to you. Did you do anything unconventional between installing, updating and rebooting? Did you install or remove additional packages?

It's ok, and no, I haven't done anything I don't normally do. I installed Vivaldi browser, ran sudo apt update && sudo apt upgrade and it broke after reboot.

**Comment by tobhe** [comment]
I would recommend you wait a bit, I am currently testing a new image because the previous one seemed to cause a different bug. I can ping you here once I know it works on my machine.

**Comment by JoshAtticus** [comment]
> I would recommend you wait a bit, I am currently testing a new image because the previous one seemed to cause a different bug. I can ping you here once I know it works on my machine.

Alright thanks

**Comment by tobhe** [comment]
Should be fixed now, tested fresh install and `apt update` + `apt upgrade` on a m2 air. Let me know if you still encounter errors!

**Comment by JoshAtticus** [comment]
Haven't reflashed but I am no longer having the issue. Will reopen if it happens again!
