### ISSUE TITLE
Upgrade to 23.10

### ISSUE THREAD

**Issue by clementperon** [tobhe/ubuntu-asahi#70]
Hi,

Just noticed that 23.10 seems supported but trying to perform an upgrade response that no new release found..

Is there a way to upgrade to 23.10 from 22.04?

```
$> sudo do-release-upgrade
Checking for a new Ubuntu release
No new release found.
```

Thanks for your help

**Comment by eslerm** [comment]
Does `do-release-upgrade --devel-release` help?

**Comment by clementperon** [comment]
Thanks @eslerm, yes it works.

FYI during the upgrade check I got the following error:

> Checking for installed snaps
> error: no snap found for "firmware-updater"

**Comment by eslerm** [comment]
Looks like the `firmware-updater` snap is/was a known upstream issue: https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/2039268

Appreciate your reports :)
