### ISSUE TITLE
EFI boot manager: Cannot load any image

### ISSUE THREAD

**Issue by Raikerian** [tobhe/ubuntu-asahi#74]
Hi, installing your latest Ubuntu 23.10 Desktop using this command:
```
curl -sL https://ubuntuasahi.org/install | bash
```

Installation itself is successful, however ubuntu fails to boot during first boot (no restart help) with these errors:

<img width="516" alt="Screenshot 2566-11-07 at 11 22 47" src="https://github.com/UbuntuAsahi/ubuntu-asahi/assets/8850270/59873571-68c5-49e3-96fb-597420d5cdd0">

Is there anything extra I am missing? Have also tried to resintall after your latest upload to fix https://github.com/UbuntuAsahi/ubuntu-asahi/issues/68#issuecomment-1797903847 but same issue.

Also I would like to eventually build/install [ubuntu 23.10 server](https://cloud-images.ubuntu.com/releases/mantic/release/), but currently your scripts work mostly with your predefined livefs images. Is there any guide on how to build those myself or do they not modify anything from the original ubuntu?

**Comment by tobhe** [comment]
Hi @Raikerian, thanks for the report! something might have gone wrong with the latest image build. I will see if I can reproduce the error and let you know once I have more info.

EDIT: I reset it to install the previous image which is known to work for now until we figured out what's wrong. The easiest solution for you might be to reinstall.

**Comment by tobhe** [comment]
@Raikerian I uploaded a new version and ran a few tests. Looks like the issue should be fixed now. Thanks again for the report, this was very helpful!

To remove your broken installation you can follow the instructions in https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet

**Comment by Raikerian** [comment]
Thank you! Will try, I already nuked it so will just reinstall later.

Any advice how I can package ubuntu server using your scripts by the way? Does it have to be livecd, or can something like https://cloud-images.ubuntu.com/releases/mantic/release/ be used?

**Comment by tobhe** [comment]
it isn't trivial I think and livecd-rootfs is a maze not many understand. I might have a chance to ask someone who works on this later today. Ideally we would have to teach launchpad to build server images, the scripts in this repo would just treat it as any other launchpad build.

**Comment by Raikerian** [comment]
Thanks, that would be helpful. My end goal is to also be able to network boot from grub (or maybe u-boot) over http, which seems to be not possible right now as u-boot doesn't support built-in apple network drivers and grub `net_ls_cards` is empty due to that. Using ethernet over usb also doesn't seem to help. If you know anything about that, would love to hear.

But as of this issue, its fixed now, thanks again.
