### ISSUE TITLE
DisplayLink on 22.04

### ISSUE THREAD

**Issue by EdvardSire** [tobhe/ubuntu-asahi#75]
Hi,
First off thank you for this repo!

I've followed through with the installer and I'm trying to get DisplayLink to work like in the image shown here: [`working demo`](https://www.reddit.com/r/AsahiLinux/comments/12pvfzn/displaylink_and_ubuntu_on_m1/)

From what i understand i need both Mesa and asahi-edge kernel.
I dug around some other issued and from what I can grep out of apt i already have mesa.

How can i switch to the asahi-edge kernel? Or can you point me in the right direction?:)

**Comment by tobhe** [comment]
Hi @EdvardSire, the asahi-edge kernel does not exist anymore since GPU acceleration is enabled by default nowadays. It should work out of the box.

**Comment by eslerm** [comment]
Please let us know if DisplayLink works for you.

(*DisplayPort* support is on upstream's roadmap.)

**Comment by EdvardSire** [comment]
Following this [guide](https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu) did not work for me. This guide has always worked for me on non macs. Do you guys have any idea how I can debug this?

**Comment by eslerm** [comment]
I'm not too familiar.

The keyring deb file adds broken urls to `/etc/apt/sources.list.d/synaptics.list`:
```
deb [signed-by=/usr/share/keyrings/synaptics-repository-keyring.gpg] https://www.synaptics.com/sites/default/files/Ubuntu/ stable main
deb [signed-by=/usr/share/keyrings/synaptics-repository-keyring.gpg] https://www.synaptics.com/sites/default/files/Ubuntu/ stable non-free
```

The `Latest Official Driver` link has a zip with a README and bash script.

**Comment by EdvardSire** [comment]
Thank you for the response:)

I removed the keyring and uninstalled `displaylink-driver`. After running the runfile in `Latest Official Driver` and rebooting it's still not working.

[This](https://discussion.fedoraproject.org/t/fedora-37-kernel-6-1-issue-with-lenovo-dock/69370/8) fedora discussion made be realize that there is a difference between the docs. 40AN vs 40AC (usb vs thunderbolt).

I indeed have a 40AC (thunderbolt) and from what i see over at the hardware [docs](https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support) it's still WIP.

And one last thing, can someone help me understand what is meant by this [comment](https://www.reddit.com/r/AsahiLinux/comments/12pvfzn/comment/jgpcnu5/) with regards to mesa?

**Comment by EdvardSire** [comment]
Can confirm that it works with a DisplayLink **usb** hub:)

**Comment by eslerm** [comment]
\o/ congrats @EdvardSire

**Comment by hamza72x** [comment]
I have followed this instruction, it started working immediately.

https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

Finally triple monitor setup.

**Comment by tobhe** [comment]
Closing because it looks like the issue was resolved
