### ISSUE TITLE
Screen Resolution 

### ISSUE THREAD

**Issue by trfhgx** [tobhe/ubuntu-asahi#76]
Operating System:

macOS version: Version 14.1.1
Ubuntu version: Latest
Laptop model: M1 macbook pro 13inch
Issue:
I successfully installed Ubuntu on my MacBook alongside macOS, but I'm experiencing difficulties with the display resolution. my laptop works only on certain screen resolutions, and when I try to boot from Ubuntu, neither the external nor the main display works properly the external monitor doesnt even turn on

Is there a method for me to manually edit a custom resolution for the main display in Ubuntu from my primary macOS environment by modifying specific files within the Ubuntu volume?

please help

**Comment by eslerm** [comment]
HDMI out for external displays is not yet supported https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support#m1-devices

**Comment by tobhe** [comment]
Closing because this should now work as confirmed by timhm on irc.
