### ISSUE TITLE
Freezing issue after lock/unlock

### ISSUE THREAD

**Issue by hamza72x** [tobhe/ubuntu-asahi#77]
Screen/App freezes after lock and unlock (twice), only (top) status bar works and a log-out does reset the freeze.

Steps:

1. Lock (Ctrl+L)
2. Unlock
3. Again Lock
4. Unlock
5. Dash/Dock will disappear, only the last opened app will work. No app will open
6. Now logout by (top) status-bar
7. Unlock/Login
8. Now unfreezes

System Info:

![image](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/48919542/c06447ed-0a94-48ac-99af-7e7a63ec5c35)

**Comment by hamza72x** [comment]
Normal/Working View:

![photo_6269308009456973567_w](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/48919542/62e3eeab-ba07-485b-b493-236a31cf4f4e)


Freezed View:

![photo_6269308009456973568_w](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/48919542/0ff2b653-bd91-4fbd-801f-6c251b1b19a6)

**Comment by hamza72x** [comment]
Normal/Working View

![image](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/48919542/49b733cc-cda7-4d8f-bcba-ac06fb0f144c)

**Comment by hamza72x** [comment]
Freezed View

![image](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/48919542/1b756492-8103-44f1-9f69-b2aaa292b8c8)

**Comment by tobhe** [comment]
Hi @hamza72x, I haven't seen this kind of bug before so it's hard to tell what might be causing it. A first possible solution I would recommend is upgrading to 23.10 to see if the problem persists there.

**Comment by hamza72x** [comment]
@tobhe using `sudo do-release-upgrade` should be good? Anything else need to do? before proceeding?

**Comment by tobhe** [comment]
I think that should be enough. After the update has finished, make sure to that the asahi ppa entry in `/etc/apt/sources.list.d/` is pointing to mantic

**Comment by hamza72x** [comment]
```list
deb http://ppa.launchpad.net/tobhe/asahi/ubuntu lunar main
deb-src http://ppa.launchpad.net/tobhe/asahi/ubuntu lunar main
```

this will be:

```list
deb http://ppa.launchpad.net/tobhe/asahi/ubuntu mantic main
deb-src http://ppa.launchpad.net/tobhe/asahi/ubuntu mantic main
```

Right?

**Comment by tobhe** [comment]
yes!

**Comment by hamza72x** [comment]
Upgraded, same things happening. Not sure what's the problem here.

**Comment by hamza72x** [comment]
Forgot to do `sudo apt update + upgrade` after the dist upgrade.
After doing so, the problem seems fixed. Thanks a lot for your replies. @tobhe

**Comment by hamza72x** [comment]
Found the actual root cause, it was `Dash to Dock` extension.
During dist upgrade, it was automatically disabled and the system was working as expected.
But when I manually enabled the extension again, the problem starts appearing, so removing this for now is the solution.
