### ISSUE TITLE
M3 support

### ISSUE THREAD

**Issue by hadim** [tobhe/ubuntu-asahi#79]
It looks like M3 is not fully supported yet (same features as for M1/M2).  See https://github.com/AsahiLinux/docs/wiki/M3-Series-Feature-Support

Once supported upstream, will that be available straight on Ubuntu Asahi? 

---

Also, more generally, I am wondering what is supported and not supported on the Ubuntu-specific side? For example, are snaps working generally?

**Comment by tobhe** [comment]
Hi @hadim. Once m3 support lands in Asahi it will also be available for Ubuntu. We try to add support for everything Asahi supports as fast as we can but we always wait for an official release first so the reference platform (Arch and soon Fedora) is usually a tiny bit faster in adding new features.

Regarding snaps: yes they are fully supported, we even came up with a way to have working GPU acceleration with our custom mesa version.

**Comment by hadim** [comment]
Thanks!

**Comment by hadim** [comment]
Hey @tobhe 

Even if most of the features are not here, is it "safe" to install Ubuntu on an M3 you think? By that I mean: I install it and a lot of features will be missing but I will be able to get those via the coming updates.

Or would you recommend not performing the installation right now and hold for more features to be available?

**Comment by tobhe** [comment]
Hi @hadim. I don't think it will work at all since no one (even in upstream Asahi) has had time to work on M3 yet. The installer should also currently not allow you to. I recommend a bit of patience, I think the Asahi folks are busy preparing their Fedora release and fixing up the last Audio and HDMI bits. Once that is done, people will have time to start with M3 support.

**Comment by hadim** [comment]
ok, got it. Thanks for the explanation!

**Comment by romain130492** [comment]
hey, any news about this by any chance!? @tobhe 
Thanks

**Comment by tobhe** [comment]
Hey @romain130492, sadly no news yet. Latest update from Asahi can be found at https://discussion.fedoraproject.org/t/asahi-on-m3/117919
