### ISSUE TITLE
Which Mac mini suggested for virtualisation use

### ISSUE THREAD

**Issue by yadvr** [tobhe/ubuntu-asahi#83]
Hi community, cc @tobhe, any advice on which Mac mini model is suggested to use with Ubuntu Asahi that can work with libvirt/qemu (such as virt-manager or cockpit-machines)? Also does Mac mini with 10G Ethernet work with reasonable performance (both latency and throughput)?

**Comment by tobhe** [comment]
M1 and M2 mini should work fine, I can't speak for the m3 since I don't own one but I think they aren't quite there yet. Virtualization should work on all of them, newer releases work better.
