### ISSUE TITLE
HDMI output is not working on Macbook Pro (M1 Pro)

### ISSUE THREAD

**Issue by dwiprawira** [tobhe/ubuntu-asahi#87]
The HDMI output is not working when connecting the MacBook to an external display. It is already working on Fedora Linux. Is there any step that I am missing to enable this feature on Asahi Ubuntu?

**Comment by tobhe** [comment]
Hi @dwiprawira, which Ubuntu version and which kernel are you running?

**Comment by dwiprawira** [comment]
Hi @tobhe I am using Ubuntu 22.04.3 LTS and kernel 6.5.0-1013-apple-arm.

**Comment by tobhe** [comment]
ok, makes sense. HDMI support is enabled in kernel 6.6 which is currently only published for 23.10. I was holding back with 22.04 because all the audio bits are a bit tricky to backport, but not much is missing.

**Comment by dwiprawira** [comment]
I have already upgraded to Ubuntu 23.10 using do-release-update command. But, the kernel is not upgraded to 6.6. Is there any way to upgrade the kernel to 6.6?

**Comment by tobhe** [comment]
Can you paste the contents of `/etc/apt/sources.list.d/asahi-ppa.list`?

**Comment by michdw** [comment]
I am having the same issue on a MacBook Air M1 after a fresh install of 23.10, and I verified that I already have Kernel 6.6
![Screenshot from 2024-02-05 01-33-21](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/16740960/ae7b5f96-b609-4d90-92ef-069aa6ce5f3a)

**Comment by tobhe** [comment]
@michdw Did you run a full package upgrade after installation? If not try that and reboot.

**Comment by ziyiwang54** [comment]
@tobhe When will the HDMI support for 22.04 coming soon?

**Comment by dooraim** [comment]
@michdw I have your problem, have you some news?

**Comment by eslerm** [comment]
According to upstream, HDMI Out is not yet supported on the M1 MacBook Air: https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support @tobhe is their information accurate?

@Andd54 Ubuntu Asahi has moved to a 9-month support window for Ubuntu releases. Upstream moves quickly, so newer releases have a better experience.

**Comment by tobhe** [comment]
> According to upstream, HDMI Out is not yet supported on the M1 MacBook Air: https://github.com/AsahiLinux/docs/wiki/M1-Series-Feature-Support @tobhe is their information accurate?

As far as I know the M1 Air doesn't have an HDMI port. Video over USB does not work yet, that includes any kind of adapter plugged into USB-C. I missed that when I first read the comment.
 
> @Andd54 Ubuntu Asahi has moved to a 9-month support window for Ubuntu releases. Upstream moves quickly, so newer releases have a better experience.

+1, keeping Jammy up-to-date with new features has been getting increasingly harder and is really hard to test. I recommend switching to a newer release if you want the latest features. We have disabled new 22.04 installations for now and decided to focus on 23.10 and 24.04 instead. Existing installations will largely continue to work but won't receive any feature updates.

**Comment by ziyiwang54** [comment]
@tobhe How about M1 MacBook Pro with an individual hdmi port? Because ROS cannot support Mantic 23.10 but only versions <=22.04. :(

**Comment by tobhe** [comment]
@Andd54 m1 macbook pro does have HDMI support in 23.10.

Regarding ROS: I understand that 22.04 is a stable ABI to target but I don't think that this justifies maintaining hardware support for 22.04 (especially since that release is older than most hardware we target now).
You can always run a newer release on bare metal to get access to the newest features and use containers for your ROS development environment.

If you prefer lxd (which is available by default on Ubuntu) this might help:
https://ubuntu.com/blog/ros-development-with-lxd
https://ubuntu.com/blog/installing-ros-in-lxd

Alternatively you can use docker:
https://wiki.ros.org/docker/Tutorials

Using containers should even allow you to use older 20.04 or 18.04 based ROS releases.

**Comment by ziyiwang54** [comment]
@tobhe Understandable, thank you! :)

**Comment by jitunayak** [comment]
In 23.10 HDMI output is working but audio output through HDMI is broken

**Comment by tobhe** [comment]
@jitunayak that is expected, there was no support for audio over hdmi until very recently. We are currently testing a kernel version that should support it so I expect it to come with an update very soon.

**Comment by tobhe** [comment]
@jitunayak HDMI audio should work on 24.04 on everything but m2 ultra.

Closing this one now since it should be resolved. Thanks everyone!
