### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by prysiu** [tobhe/ubuntu-asahi#89]
https://tobhe.de/ubuntu/os/ubuntu-desktop-23.10-20231019.zip

**Comment by tobhe** [comment]
Thanks! I think this was broken in one of our recent commits to the website here: https://github.com/UbuntuAsahi/ubuntuasahi.github.io and should be fixed now with https://github.com/UbuntuAsahi/ubuntuasahi.github.io/commit/0942e20210214c87e393cfeee11cd803d6e546bf
