### ISSUE TITLE
your system did not boot into correct recovery

### ISSUE THREAD

**Issue by cskn95** [tobhe/ubuntu-asahi#94]
I'm using M2 Air with Sonoma 14.3.1 and tried to install Ubuntu 23.10. When the machine has shut down and I reopen after a minute and choose Ubuntu on startup menu, a login page appears and after that in a terminal it says "your system did not boot into correct recovery" and wants my login info to shutdown. I tried 3 times but no changes.

**Comment by tobhe** [comment]
Hi! Please try booting into macos and run the installer a second time. It should give you a repair option.
Let us know if the problem persists after the repair!

**Comment by cskn95** [comment]
> Hi! Please try booting into macos and run the installer a second time. It should give you a repair option. Let us know if the problem persists after the repair!

I tried but nothing changed. I tried repair option 2 times and even tried to install Fedora Remix version from Asahi Linux web page (before I completely removed Ubuntu Asahi) but nothing changes. I'm doing exactly what it says, I even watched videos and nope, I'm doing it right, sure about it.

**Comment by tobhe** [comment]
Weird. Does a fresh Fedora install work? This is new to me, I'll try and run a fresh install on my test hardware.

**Comment by cskn95** [comment]
3rd installation attempt worked fine interestingly. Sorry to bother you, everything seems like works fine.

**Comment by tobhe** [comment]
Thank you for the report! We rely on our community to notify us if anything goes wrong because we can't test every possible combination of hardware and software ourselves. Your feedback is very much appreciated :) Glad it turned out not to be a bigger issue.
