### ISSUE TITLE
Add more space to "free space" 

### ISSUE THREAD

**Issue by MWRevamped** [tobhe/ubuntu-asahi#97]
I'm not that familiar with operating systems for computers other than Windows and OSX, but I've always wanted to try some out, and I set Ubuntu up without failure but I didn't give that much space to my Ubuntu partition and I want some more space for it, is there a way I can repartition more to it? it says it can't be resized in disk utility.

<img width="382" alt="Screenshot 2024-03-02 at 10 10 05 AM" src="https://github.com/UbuntuAsahi/ubuntu-asahi/assets/118232870/9207aef8-e993-42c1-a259-7481c404b497">

**Comment by eslerm** [comment]
This operation is not simple to perform. First you would need to resize the apfs containers, then the asahi partition, and then the asahi filesystem, in that order. This would require another linux os for some of the steps, likely with a live cd in this case. I can't vouch for [this guide](https://www.reddit.com/r/AsahiLinux/comments/10xn538/guide_how_to_resize_your_asahi_root_partition/) but it seems to be on the right track.

I recommend backing up, wiping, and reinstalling.

**Comment by MWRevamped** [comment]
Aw alright, thank you for the response tho, have a good day!
